### ISSUE TITLE
Set up CI to run flake8

### ISSUE THREAD

**Issue by Spindel** [csansone/simpletrello#1]
[Travis](https://docs.travis-ci.com/user/getting-started/) is the recommended GitHub tool for CI builds.

A minimal example would be:
```
  language: python
  python:
    - 3.6
    - nightly
  script:
    - pip install flake8
    - pip install -r requirements.txt
    - flake8 .
```
